### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by EHanz**

### CODE REVIEW

**Comment by EHanz** [comment]
PLZ DO THIS AAAA

**Comment by jkcarney** [comment]
this isnt up to my quality standards

**Comment by EHanz** [comment]
Added @astruxie since her team is in charge of README

**Comment by samnoggle** [comment]
Ggjdjkd ff jh?????

**Comment by jkcarney** [comment]
Aaaii JSDHDHSSJAJJJ AAAAAFHJJXBFNS

**Comment by EHanz** [comment]
AAAAAA GHSFSGFTKCMSBRTBFKKD

**Review by samnoggle — APPROVED** [review]
never contact me again or request my review. I am blocking u now

**Comment by jkcarney** [comment]
@astruxie please stop emailing me. I'm a busy man

**Comment by EHanz** [comment]
Can we move this convo to Teams? This is very inefficient

**Comment by jkcarney** [comment]
Dear @EHanz 

What did I just say about emailing me. Stop it. Some of us have day jobs and don't have time for your open source crusades

**Pull request merged**
